// Command axt-docgen renders reference documentation from code, so it cannot
// drift from the implementation. Currently it emits the configuration
// reference from the same declarations config.Load uses to parse the
// environment.
//
//	go run ./cmd/axt-docgen config > ../docs/configuration.md
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/axt-term/axt-term/backend/internal/config"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: axt-docgen config")
		os.Exit(2)
	}
	switch os.Args[1] {
	case "config":
		if err := writeConfigDocs(os.Stdout); err != nil {
			fmt.Fprintf(os.Stderr, "axt-docgen: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "axt-docgen: unknown target %q\n", os.Args[1])
		os.Exit(2)
	}
}

func writeConfigDocs(w *os.File) error {
	fields := config.Describe()
	sort.SliceStable(fields, func(i, j int) bool { return fields[i].Key < fields[j].Key })

	var b strings.Builder
	b.WriteString("# Configuration Reference\n\n")
	b.WriteString("<!-- Generated by `make docs-config`. Edit backend/internal/config/config.go instead. -->\n\n")
	b.WriteString("Every setting is an environment variable. AXT-Term validates all of them at\n")
	b.WriteString("startup and refuses to run if any is invalid, reporting every problem at once.\n\n")
	b.WriteString("Variables marked **secret** are masked in logs and in the startup banner.\n\n")
	b.WriteString("| Variable | Type | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")

	for _, f := range fields {
		kind := f.Kind
		if len(f.Allowed) > 0 {
			kind = "`" + strings.Join(f.Allowed, "` \\| `") + "`"
		}
		def := f.Default
		if def == "" {
			def = "—"
		} else {
			def = "`" + def + "`"
		}
		name := "`" + f.Key + "`"
		if f.Secret {
			name += " **secret**"
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", name, kind, def, escapePipes(f.Doc))
	}

	_, err := w.WriteString(b.String())
	return err
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
