/** Types mirroring the Go API. Generated by `make types` (tygo) in the final
 * setup; hand-maintained here until that step runs, with the Go structs in
 * internal/store and internal/api as the source of truth. */

export type Protocol = 'ssh' | 'sftp' | 'rdp' | 'vnc' | 'telnet' | 'serial' | 'winrm'
export type OSFamily = 'linux' | 'windows' | 'bsd' | 'macos' | 'network' | 'unknown'
export type AuthMethod = 'credential' | 'agent' | 'password_prompt' | 'key_prompt'
export type CommandLogging = 'inherit' | 'off' | 'commands' | 'full'
export type HealthStatus = 'online' | 'slow' | 'offline' | 'unknown'
export type CredentialKind = 'password' | 'ssh_key' | 'ssh_agent' | 'rdp_password'
export type SnippetRunMode = 'insert' | 'run'

/**
 * Session state. The distinction between `detached` and `disconnected` is
 * load-bearing: a detached session is alive and will accept input again, a
 * disconnected one is frozen history. Conflating them is how a user comes to
 * believe they restarted a service when the keystroke went nowhere.
 */
export type SessionState =
  | 'connecting'
  | 'connected'
  | 'detached'
  | 'disconnected'
  | 'failed'
  | 'closed'

export interface User {
  id: string
  username: string
  display_name: string
  email?: string
  roles: string[]
  permissions: string[]
  must_change_password: boolean
  last_login_at?: string
}

export interface MeResponse {
  user: User
  instance: string
  rdp_enabled: boolean
  live_sessions: number
}

export interface HostHealth {
  host_id: string
  status: HealthStatus
  latency_ms?: number
  checked_at: string
  error?: string
}

/**
 * Per-host RDP settings, which also carry the VNC ones: both protocols reach the
 * browser through the same guacd bridge and share most of what matters. Clipboard
 * and drive redirection are off unless set — each is a bidirectional data path into
 * the host.
 */
export interface RDPOptions {
  domain?: string
  security?: string
  ignore_cert?: boolean
  enable_clipboard?: boolean
  enable_drive?: boolean
  drive_path?: string
  enable_audio?: boolean
  enable_printing?: boolean
  initial_width?: number
  initial_height?: number
  color_depth?: number
  disable_wallpaper?: boolean
  resize_method?: string
  remote_app?: string
  preconnection_blob?: string

  /* RDP, less commonly set. */
  console?: boolean
  server_layout?: string
  timezone?: string
  enable_theming?: boolean
  enable_font_smoothing?: boolean

  /* VNC. */
  swap_red_blue?: boolean
  cursor?: string
  read_only?: boolean
  clipboard_encoding?: string
}

export interface Host {
  id: string
  name: string
  hostname: string
  port: number
  protocol: Protocol
  folder_id: string
  username: string
  auth_method: AuthMethod
  credential_id: string
  jump_host_id: string
  os_family: OSFamily
  color: string
  icon: string
  notes: string
  is_favorite: boolean
  sort_order: number
  health_check_enabled: boolean
  health_check_interval_s: number
  command_logging: CommandLogging
  rdp_options: RDPOptions
  created_by: string
  created_at: string
  updated_at: string
  tags: string[]
  folder_path?: string
  health?: HostHealth
}

export interface Folder {
  id: string
  parent_id: string
  name: string
  icon: string
  color: string
  sort_order: number
  path?: string
}

export interface Tag {
  id: string
  name: string
  color: string
  count?: number
}

/** Note the absence of any secret field: the server has nowhere to put one. */
export interface Credential {
  id: string
  name: string
  kind: CredentialKind
  provider: string
  username: string
  domain?: string
  key_type?: string
  key_fingerprint?: string
  key_comment?: string
  notes: string
  key_version: number
  has_password: boolean
  has_private_key: boolean
  has_passphrase: boolean
  in_use_by_count: number
  created_at: string
  updated_at: string
  last_used_at?: string
}

export interface SnippetVariable {
  name: string
  label?: string
  default?: string
  required?: boolean
  source?: string
}

export interface Snippet {
  id: string
  folder_id: string
  name: string
  description: string
  body: string
  shell: string
  os_family?: string
  variables: SnippetVariable[]
  is_favorite: boolean
  hotkey?: string
  run_mode: SnippetRunMode
  use_count: number
  created_at: string
  updated_at: string
}

export interface SnippetFolder {
  id: string
  parent_id: string
  name: string
  sort_order: number
}

/**
 * A live session, terminal or desktop.
 *
 * A PTY measures itself in cells and a desktop in pixels, so the two pairs of
 * fields are both optional rather than one pair pretending to mean both.
 */
export interface SessionInfo {
  id: string
  user_id: string
  host_id: string
  host_label: string
  protocol: Protocol
  state: SessionState
  cols?: number
  rows?: number
  width?: number
  height?: number
  attachments: number
  seq?: number
  bytes_in: number
  bytes_out: number
  recording?: boolean
  exit_reason?: string
  created_at: string
  detached_for_s?: number
  session_record_id?: string
}

export interface HostKeyPrompt {
  hostname: string
  port: number
  key_type: string
  fingerprint: string
  first_contact: boolean
}

export interface CreateSessionResponse {
  session_id?: string
  state: SessionState | 'pending_hostkey'
  host?: Host
  session?: SessionInfo
  pending_hostkey?: HostKeyPrompt
  banners?: string[]
}

export interface TicketResponse {
  ticket: string
  expires_in: number
  seq: number
}

export interface HostAction {
  id: string
  label: string
  icon: string
  group: string
  permission: string
  implemented: boolean
  phase?: string
}

export interface ProbeResult {
  reachable: boolean
  latency_ms: number
  banner?: string
  error?: string
}

export interface SessionRecord {
  id: string
  host_id: string
  host_snapshot: string
  protocol: Protocol
  status: string
  started_at: string
  ended_at?: string
  exit_reason?: string
  host_name?: string
}

export interface Transfer {
  id: string
  host_id: string
  direction: 'upload' | 'download'
  remote_path: string
  display_name: string
  size_bytes?: number
  transferred_bytes: number
  status: 'queued' | 'active' | 'completed' | 'failed' | 'cancelled' | 'interrupted'
  error?: string
  speed_bps: number
  retry_count: number
  queued_at: string
  host_name?: string
}

export interface SearchResult {
  kind: 'host' | 'folder' | 'snippet' | 'tag' | 'workspace' | 'session'
  id: string
  title: string
  subtitle?: string
  protocol?: string
}

export interface AuditEvent {
  id: number
  ts: string
  user_id?: string
  username: string
  host_id?: string
  host_snapshot?: string
  action: string
  target?: string
  result: 'success' | 'failure' | 'denied'
  severity: 'info' | 'notice' | 'warning' | 'critical'
  client_ip?: string
  detail?: Record<string, unknown>
  request_id?: string
}
